stages:
  - build
  - lint
  - test

build-frontend:
  stage: build
  image: node:lts
  artifacts:
    expire_in: 1 day
    paths:
      - frontend/node_modules
  variables:
    CI: "false"  # Set CI to false for this job
  script:
    - cd frontend/
    - export REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
    - export REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
    - export REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL}
    - npm install
    - npm run build

lint-frontend:
  stage: lint
  image: node:lts
  artifacts:
    expire_in: 1 day
    paths:
      - frontend/node_modules
  variables:
    CI: "false"  # Set CI to false for this job
  before_script:
    - npm install eslint
    - npm install typescript 
    - npm install eslint-plugin-react
    - npm install eslint-plugin-react-hooks
    - npm install eslint-plugin-spellcheck
    - npm install @stylistic/eslint-plugin
    - npm install @typescript-eslint/parser
    - npm install @typescript-eslint/eslint-plugin eslint
  script:
    - cd frontend/
    - npx eslint ./src/ --quiet

lint-backend:
  stage: lint
  image: stgit.dcs.gla.ac.uk:5050/team-project-h/2023/sh30/cs30-main:latest
  before_script:
    - cd api/
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
  script:
    - cd ../ 
    - pylint ./api/ --rcfile .pylintrc --ignore=.env
  dependencies: []

test-frontend:
  stage: test
  image: node:latest
  needs:
    - build-frontend
  dependencies:
    - build-frontend
  script:
    - cd frontend/
    - npm test

test-backend:
  stage: test
  image: stgit.dcs.gla.ac.uk:5050/team-project-h/2023/sh30/cs30-main:latest
  only:
    variables:
      - $NIGHTLY_TEST
  before_script:
    - cd api/
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - python3 setup.py install 
  script:
    - cd ../tests/
    - ./runtests.sh
  dependencies: []
