# Use official python 3.10 docker image
image: python:3.10.12

# Run these commands in the docker container before each job
before_script:
  - python --version
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

stages:
  - Linting

pylint:
  stage: Linting
  script:
  - pylint ./src --rcfile .pylintrc