stages:
  - build
  - lint

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd frontend/
    - npm install
    - npm run build

lint-backend:
  stage: lint
  image: stgit.dcs.gla.ac.uk:5050/team-project-h/2023/sh30/cs30-main:latest
  before_script:
    - cd backend/
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
  script:
    - cd ../ 
    - pylint ./backend/ --rcfile .pylintrc