version: '3'

services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    restart: always
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    network_mode: "host"
    restart: always
    command: python3 app.py
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on: 
      - db

volumes:
  db:
    driver: local